export enum COLORS {
  LAVENDER = "#E2CFEA",
  AMETHYST = "#A06CD5",
  PURPLE = "#6247AA",
  BLUE = "#102B3F",
  GREEN = "#062726",
}

export const MARGIN = { top: 40, right: 20, bottom: 40, left: 40 };

export const INVISIBLE_VALUE = -Infinity;

export const TRANSITION_DURATION = 250;

export enum ExampleName {
  PLAYGROUND = "PLAYGROUND",
  REACT_BAR_CHART = "REACT_BAR_CHART",
  D3_BAR_CHART = "D3_BAR_CHART",
  D3_STACKED_BAR_CHART = "D3_STACKED_BAR_CHART",
  LINE_CHART = "LINE_CHART",
  PIE_CHART = "PIE_CHART",
  CANVAS_EXAMPLE = "CANVAS_EXAMPLE",
  CANVAS_CHART = "CANVAS_CHART",
}
